/// Cien personas de prueba, con la forma exacta del modelo de identidad.
///
/// No es una lista de nombres: cada una trae lo que el SDK necesita para
/// demostrar las tres cosas que hay que poder probar sin un comercio real.
///
///   **alias** — cédula y correo. Son por los que se DIRECCIONA: únicos dentro
///   del comercio, y se puede enviar a cualquiera de los dos. Es lo que permite
///   probar «mandale a la cédula 12137717» sin saber su `userId`.
///
///   **atributos** — nombre, sucursal, ciudad y plan. Son para FILTRAR y
///   MOSTRAR, no para direccionar. Es lo que permite probar el envío segmentado
///   —«a todos los de CCS-01», «a los del plan Bronce»— y la búsqueda en la
///   consola.
///
/// Los datos están repartidos a propósito: ocho ciudades, tres sucursales en
/// cada una y cuatro planes, de modo que cualquier filtro devuelva un grupo de
/// tamaño razonable y no uno ni cien. Un juego de prueba donde todos comparten
/// el mismo valor no prueba el filtro: prueba que la consulta corre.
///
/// **Todas entran con la misma clave: `admin123`**, y el usuario es `usuario1`
/// hasta `usuario100`. Es un juego de prueba: la clave es igual para las cien a
/// propósito, para poder entrar con cualquiera sin ir a buscarla.
///
/// 🔴 Y por eso mismo: esto NO se usa fuera de un ambiente de prueba. Cien
/// cuentas con la misma clave conocida es exactamente lo que no se hace en
/// ningún lado donde haya datos de alguien.
///
/// Las cédulas y los correos son inventados y no corresponden a nadie.
library;

/// Una persona del juego de prueba.
class PersonaDePrueba {
  const PersonaDePrueba({
    required this.userId,
    required this.usuario,
    required this.cedula,
    required this.correo,
    required this.nombre,
    required this.sucursal,
    required this.ciudad,
    required this.plan,
  });

  /// La clave con la que el comercio la identifica. Opaca para el SDK.
  final String userId;

  /// Con qué entra: `usuario1` … `usuario100`. La contraseña es [claveDePrueba]
  /// para todas.
  final String usuario;

  // ── alias · se direcciona por acá ──────────────────────────────────────
  final String cedula;
  final String correo;

  // ── atributos · se filtra y se muestra por acá ─────────────────────────
  final String nombre;
  final String sucursal;
  final String ciudad;
  final String plan;

  /// Lo que el backend del comercio le mandaría al servicio para darla de alta.
  Map<String, dynamic> get comoAlta => {
        'userId': userId,
        'alias': {'cedula': cedula, 'correo': correo},
        'atributos': {
          'nombre': nombre,
          'sucursal': sucursal,
          'ciudad': ciudad,
          'plan': plan,
        },
      };

  @override
  String toString() => '$usuario · $nombre · $cedula · $sucursal · $plan';
}

/// Las cien.
/// La contraseña de las cien. Igual para todas, a propósito y sólo para probar.
const claveDePrueba = 'admin123';

const cienPersonas = <PersonaDePrueba>[
  PersonaDePrueba(
    userId: 'u_9000',
    usuario: 'usuario1',
    cedula: '12137717',
    correo: 'ana.rodriguez0@ejemplo.com',
    nombre: 'Ana Rodríguez',
    sucursal: 'CCS-01',
    ciudad: 'Caracas',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9001',
    usuario: 'usuario2',
    cedula: '12276345',
    correo: 'miguel.rivas1@ejemplo.com',
    nombre: 'Miguel Rivas',
    sucursal: 'MCB-02',
    ciudad: 'Maracaibo',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9002',
    usuario: 'usuario3',
    cedula: '12415884',
    correo: 'marisol.colmenares2@ejemplo.com',
    nombre: 'Marisol Colmenares',
    sucursal: 'VAL-03',
    ciudad: 'Valencia',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9003',
    usuario: 'usuario4',
    cedula: '12556334',
    correo: 'douglas.hernandez3@ejemplo.com',
    nombre: 'Douglas Hernández',
    sucursal: 'BQT-01',
    ciudad: 'Barquisimeto',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: 'u_9004',
    usuario: 'usuario5',
    cedula: '12697695',
    correo: 'yusmary.guerra4@ejemplo.com',
    nombre: 'Yusmary Guerra',
    sucursal: 'CBL-02',
    ciudad: 'Ciudad Bolívar',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9005',
    usuario: 'usuario6',
    cedula: '12839967',
    correo: 'nestor.quintero5@ejemplo.com',
    nombre: 'Néstor Quintero',
    sucursal: 'MCY-03',
    ciudad: 'Maracay',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9006',
    usuario: 'usuario7',
    cedula: '12983150',
    correo: 'aixa.lopez6@ejemplo.com',
    nombre: 'Aixa López',
    sucursal: 'MTR-01',
    ciudad: 'Maturín',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9007',
    usuario: 'usuario8',
    cedula: '13127244',
    correo: 'simon.rojas7@ejemplo.com',
    nombre: 'Simón Rojas',
    sucursal: 'SCR-02',
    ciudad: 'San Cristóbal',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: 'u_9008',
    usuario: 'usuario9',
    cedula: '13272249',
    correo: 'rosa.suarez8@ejemplo.com',
    nombre: 'Rosa Suárez',
    sucursal: 'CCS-03',
    ciudad: 'Caracas',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9009',
    usuario: 'usuario10',
    cedula: '13418165',
    correo: 'jesús.torres9@ejemplo.com',
    nombre: 'Jesús Torres',
    sucursal: 'MCB-01',
    ciudad: 'Maracaibo',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9010',
    usuario: 'usuario11',
    cedula: '13564992',
    correo: 'yajaira.medina10@ejemplo.com',
    nombre: 'Yajaira Medina',
    sucursal: 'VAL-02',
    ciudad: 'Valencia',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9011',
    usuario: 'usuario12',
    cedula: '13712730',
    correo: 'alexander.gonzalez11@ejemplo.com',
    nombre: 'Alexander González',
    sucursal: 'BQT-03',
    ciudad: 'Barquisimeto',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: 'u_9012',
    usuario: 'usuario13',
    cedula: '13861379',
    correo: 'katiuska.blanco12@ejemplo.com',
    nombre: 'Katiuska Blanco',
    sucursal: 'CBL-01',
    ciudad: 'Ciudad Bolívar',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9013',
    usuario: 'usuario14',
    cedula: '14010939',
    correo: 'jhonny.bastidas13@ejemplo.com',
    nombre: 'Jhonny Bastidas',
    sucursal: 'MCY-02',
    ciudad: 'Maracay',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9014',
    usuario: 'usuario15',
    cedula: '14161410',
    correo: 'yaritza.garcia14@ejemplo.com',
    nombre: 'Yaritza García',
    sucursal: 'MTR-03',
    ciudad: 'Maturín',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9015',
    usuario: 'usuario16',
    cedula: '14312792',
    correo: 'pedro.mendoza15@ejemplo.com',
    nombre: 'Pedro Mendoza',
    sucursal: 'SCR-01',
    ciudad: 'San Cristóbal',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: 'u_9016',
    usuario: 'usuario17',
    cedula: '14465085',
    correo: 'gladys.pacheco16@ejemplo.com',
    nombre: 'Gladys Pacheco',
    sucursal: 'CCS-02',
    ciudad: 'Caracas',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9017',
    usuario: 'usuario18',
    cedula: '14618289',
    correo: 'argenis.sanchez17@ejemplo.com',
    nombre: 'Argenis Sánchez',
    sucursal: 'MCB-03',
    ciudad: 'Maracaibo',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9018',
    usuario: 'usuario19',
    cedula: '14772404',
    correo: 'nairobi.castillo18@ejemplo.com',
    nombre: 'Nairobi Castillo',
    sucursal: 'VAL-01',
    ciudad: 'Valencia',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9019',
    usuario: 'usuario20',
    cedula: '14927430',
    correo: 'gustavo.villalobos19@ejemplo.com',
    nombre: 'Gustavo Villalobos',
    sucursal: 'BQT-02',
    ciudad: 'Barquisimeto',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: 'u_9020',
    usuario: 'usuario21',
    cedula: '15083367',
    correo: 'coromoto.flores20@ejemplo.com',
    nombre: 'Coromoto Flores',
    sucursal: 'CBL-03',
    ciudad: 'Ciudad Bolívar',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9021',
    usuario: 'usuario22',
    cedula: '15240215',
    correo: 'osmel.salazar21@ejemplo.com',
    nombre: 'Osmel Salazar',
    sucursal: 'MCY-01',
    ciudad: 'Maracay',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9022',
    usuario: 'usuario23',
    cedula: '15397974',
    correo: 'carmen.perez22@ejemplo.com',
    nombre: 'Carmen Pérez',
    sucursal: 'MTR-02',
    ciudad: 'Maturín',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9023',
    usuario: 'usuario24',
    cedula: '15556644',
    correo: 'rafael.moreno23@ejemplo.com',
    nombre: 'Rafael Moreno',
    sucursal: 'SCR-03',
    ciudad: 'San Cristóbal',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: 'u_9024',
    usuario: 'usuario25',
    cedula: '15716225',
    correo: 'nelida.marcano24@ejemplo.com',
    nombre: 'Nélida Marcano',
    sucursal: 'CCS-01',
    ciudad: 'Caracas',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9025',
    usuario: 'usuario26',
    cedula: '15876717',
    correo: 'orlando.martinez25@ejemplo.com',
    nombre: 'Orlando Martínez',
    sucursal: 'MCB-02',
    ciudad: 'Maracaibo',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9026',
    usuario: 'usuario27',
    cedula: '16038120',
    correo: 'solange.silva26@ejemplo.com',
    nombre: 'Solange Silva',
    sucursal: 'VAL-03',
    ciudad: 'Valencia',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9027',
    usuario: 'usuario28',
    cedula: '16200434',
    correo: 'edgar.zambrano27@ejemplo.com',
    nombre: 'Edgar Zambrano',
    sucursal: 'BQT-01',
    ciudad: 'Barquisimeto',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: 'u_9028',
    usuario: 'usuario29',
    cedula: '16363659',
    correo: 'nakary.ramirez28@ejemplo.com',
    nombre: 'Nakary Ramírez',
    sucursal: 'CBL-02',
    ciudad: 'Ciudad Bolívar',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9029',
    usuario: 'usuario30',
    cedula: '16527795',
    correo: 'jose.vargas29@ejemplo.com',
    nombre: 'José Vargas',
    sucursal: 'MCY-03',
    ciudad: 'Maracay',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9030',
    usuario: 'usuario31',
    cedula: '16692842',
    correo: 'yolanda.rodriguez30@ejemplo.com',
    nombre: 'Yolanda Rodríguez',
    sucursal: 'MTR-01',
    ciudad: 'Maturín',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9031',
    usuario: 'usuario32',
    cedula: '16858800',
    correo: 'franklin.rivas31@ejemplo.com',
    nombre: 'Franklin Rivas',
    sucursal: 'SCR-02',
    ciudad: 'San Cristóbal',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: 'u_9032',
    usuario: 'usuario33',
    cedula: '17025669',
    correo: 'belkis.colmenares32@ejemplo.com',
    nombre: 'Belkis Colmenares',
    sucursal: 'CCS-03',
    ciudad: 'Caracas',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9033',
    usuario: 'usuario34',
    cedula: '17193449',
    correo: 'freddy.hernandez33@ejemplo.com',
    nombre: 'Freddy Hernández',
    sucursal: 'MCB-01',
    ciudad: 'Maracaibo',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9034',
    usuario: 'usuario35',
    cedula: '17362140',
    correo: 'morella.guerra34@ejemplo.com',
    nombre: 'Morella Guerra',
    sucursal: 'VAL-02',
    ciudad: 'Valencia',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9035',
    usuario: 'usuario36',
    cedula: '17531742',
    correo: 'eleazar.quintero35@ejemplo.com',
    nombre: 'Eleazar Quintero',
    sucursal: 'BQT-03',
    ciudad: 'Barquisimeto',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: 'u_9036',
    usuario: 'usuario37',
    cedula: '17702255',
    correo: 'maria.lopez36@ejemplo.com',
    nombre: 'María López',
    sucursal: 'CBL-01',
    ciudad: 'Ciudad Bolívar',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9037',
    usuario: 'usuario38',
    cedula: '17873679',
    correo: 'carlos.rojas37@ejemplo.com',
    nombre: 'Carlos Rojas',
    sucursal: 'MCY-02',
    ciudad: 'Maracay',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9038',
    usuario: 'usuario39',
    cedula: '18046014',
    correo: 'zulay.suarez38@ejemplo.com',
    nombre: 'Zulay Suárez',
    sucursal: 'MTR-03',
    ciudad: 'Maturín',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9039',
    usuario: 'usuario40',
    cedula: '18219260',
    correo: 'wilmer.torres39@ejemplo.com',
    nombre: 'Wilmer Torres',
    sucursal: 'SCR-01',
    ciudad: 'San Cristóbal',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: 'u_9040',
    usuario: 'usuario41',
    cedula: '18393417',
    correo: 'deisy.medina40@ejemplo.com',
    nombre: 'Deisy Medina',
    sucursal: 'CCS-02',
    ciudad: 'Caracas',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9041',
    usuario: 'usuario42',
    cedula: '18568485',
    correo: 'anibal.gonzalez41@ejemplo.com',
    nombre: 'Aníbal González',
    sucursal: 'MCB-03',
    ciudad: 'Maracaibo',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9042',
    usuario: 'usuario43',
    cedula: '18744464',
    correo: 'rosalba.blanco42@ejemplo.com',
    nombre: 'Rosalba Blanco',
    sucursal: 'VAL-01',
    ciudad: 'Valencia',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9043',
    usuario: 'usuario44',
    cedula: '18921354',
    correo: 'luis.bastidas43@ejemplo.com',
    nombre: 'Luis Bastidas',
    sucursal: 'BQT-02',
    ciudad: 'Barquisimeto',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: 'u_9044',
    usuario: 'usuario45',
    cedula: '19099155',
    correo: 'elena.garcia44@ejemplo.com',
    nombre: 'Elena García',
    sucursal: 'CBL-03',
    ciudad: 'Ciudad Bolívar',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9045',
    usuario: 'usuario46',
    cedula: '19277867',
    correo: 'antonio.mendoza45@ejemplo.com',
    nombre: 'Antonio Mendoza',
    sucursal: 'MCY-01',
    ciudad: 'Maracay',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9046',
    usuario: 'usuario47',
    cedula: '19457490',
    correo: 'milagros.pacheco46@ejemplo.com',
    nombre: 'Milagros Pacheco',
    sucursal: 'MTR-02',
    ciudad: 'Maturín',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9047',
    usuario: 'usuario48',
    cedula: '19638024',
    correo: 'ramon.sanchez47@ejemplo.com',
    nombre: 'Ramón Sánchez',
    sucursal: 'SCR-03',
    ciudad: 'San Cristóbal',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: 'u_9048',
    usuario: 'usuario49',
    cedula: '19819469',
    correo: 'yenifer.castillo48@ejemplo.com',
    nombre: 'Yenifer Castillo',
    sucursal: 'CCS-01',
    ciudad: 'Caracas',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9049',
    usuario: 'usuario50',
    cedula: '20001825',
    correo: 'wladimir.villalobos49@ejemplo.com',
    nombre: 'Wladimir Villalobos',
    sucursal: 'MCB-02',
    ciudad: 'Maracaibo',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9050',
    usuario: 'usuario51',
    cedula: '20185092',
    correo: 'ana.flores50@ejemplo.com',
    nombre: 'Ana Flores',
    sucursal: 'VAL-03',
    ciudad: 'Valencia',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9051',
    usuario: 'usuario52',
    cedula: '20369270',
    correo: 'miguel.salazar51@ejemplo.com',
    nombre: 'Miguel Salazar',
    sucursal: 'BQT-01',
    ciudad: 'Barquisimeto',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: 'u_9052',
    usuario: 'usuario53',
    cedula: '20554359',
    correo: 'marisol.perez52@ejemplo.com',
    nombre: 'Marisol Pérez',
    sucursal: 'CBL-02',
    ciudad: 'Ciudad Bolívar',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9053',
    usuario: 'usuario54',
    cedula: '20740359',
    correo: 'douglas.moreno53@ejemplo.com',
    nombre: 'Douglas Moreno',
    sucursal: 'MCY-03',
    ciudad: 'Maracay',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9054',
    usuario: 'usuario55',
    cedula: '20927270',
    correo: 'yusmary.marcano54@ejemplo.com',
    nombre: 'Yusmary Marcano',
    sucursal: 'MTR-01',
    ciudad: 'Maturín',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9055',
    usuario: 'usuario56',
    cedula: '21115092',
    correo: 'nestor.martinez55@ejemplo.com',
    nombre: 'Néstor Martínez',
    sucursal: 'SCR-02',
    ciudad: 'San Cristóbal',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: 'u_9056',
    usuario: 'usuario57',
    cedula: '21303825',
    correo: 'aixa.silva56@ejemplo.com',
    nombre: 'Aixa Silva',
    sucursal: 'CCS-03',
    ciudad: 'Caracas',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9057',
    usuario: 'usuario58',
    cedula: '21493469',
    correo: 'simon.zambrano57@ejemplo.com',
    nombre: 'Simón Zambrano',
    sucursal: 'MCB-01',
    ciudad: 'Maracaibo',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9058',
    usuario: 'usuario59',
    cedula: '21684024',
    correo: 'rosa.ramirez58@ejemplo.com',
    nombre: 'Rosa Ramírez',
    sucursal: 'VAL-02',
    ciudad: 'Valencia',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9059',
    usuario: 'usuario60',
    cedula: '21875490',
    correo: 'jesús.vargas59@ejemplo.com',
    nombre: 'Jesús Vargas',
    sucursal: 'BQT-03',
    ciudad: 'Barquisimeto',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: 'u_9060',
    usuario: 'usuario61',
    cedula: '22067867',
    correo: 'yajaira.rodriguez60@ejemplo.com',
    nombre: 'Yajaira Rodríguez',
    sucursal: 'CBL-01',
    ciudad: 'Ciudad Bolívar',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9061',
    usuario: 'usuario62',
    cedula: '22261155',
    correo: 'alexander.rivas61@ejemplo.com',
    nombre: 'Alexander Rivas',
    sucursal: 'MCY-02',
    ciudad: 'Maracay',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9062',
    usuario: 'usuario63',
    cedula: '22455354',
    correo: 'katiuska.colmenares62@ejemplo.com',
    nombre: 'Katiuska Colmenares',
    sucursal: 'MTR-03',
    ciudad: 'Maturín',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9063',
    usuario: 'usuario64',
    cedula: '22650464',
    correo: 'jhonny.hernandez63@ejemplo.com',
    nombre: 'Jhonny Hernández',
    sucursal: 'SCR-01',
    ciudad: 'San Cristóbal',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: 'u_9064',
    usuario: 'usuario65',
    cedula: '22846485',
    correo: 'yaritza.guerra64@ejemplo.com',
    nombre: 'Yaritza Guerra',
    sucursal: 'CCS-02',
    ciudad: 'Caracas',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9065',
    usuario: 'usuario66',
    cedula: '23043417',
    correo: 'pedro.quintero65@ejemplo.com',
    nombre: 'Pedro Quintero',
    sucursal: 'MCB-03',
    ciudad: 'Maracaibo',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9066',
    usuario: 'usuario67',
    cedula: '23241260',
    correo: 'gladys.lopez66@ejemplo.com',
    nombre: 'Gladys López',
    sucursal: 'VAL-01',
    ciudad: 'Valencia',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9067',
    usuario: 'usuario68',
    cedula: '23440014',
    correo: 'argenis.rojas67@ejemplo.com',
    nombre: 'Argenis Rojas',
    sucursal: 'BQT-02',
    ciudad: 'Barquisimeto',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: 'u_9068',
    usuario: 'usuario69',
    cedula: '23639679',
    correo: 'nairobi.suarez68@ejemplo.com',
    nombre: 'Nairobi Suárez',
    sucursal: 'CBL-03',
    ciudad: 'Ciudad Bolívar',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9069',
    usuario: 'usuario70',
    cedula: '23840255',
    correo: 'gustavo.torres69@ejemplo.com',
    nombre: 'Gustavo Torres',
    sucursal: 'MCY-01',
    ciudad: 'Maracay',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9070',
    usuario: 'usuario71',
    cedula: '24041742',
    correo: 'coromoto.medina70@ejemplo.com',
    nombre: 'Coromoto Medina',
    sucursal: 'MTR-02',
    ciudad: 'Maturín',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9071',
    usuario: 'usuario72',
    cedula: '24244140',
    correo: 'osmel.gonzalez71@ejemplo.com',
    nombre: 'Osmel González',
    sucursal: 'SCR-03',
    ciudad: 'San Cristóbal',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: 'u_9072',
    usuario: 'usuario73',
    cedula: '24447449',
    correo: 'carmen.blanco72@ejemplo.com',
    nombre: 'Carmen Blanco',
    sucursal: 'CCS-01',
    ciudad: 'Caracas',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9073',
    usuario: 'usuario74',
    cedula: '24651669',
    correo: 'rafael.bastidas73@ejemplo.com',
    nombre: 'Rafael Bastidas',
    sucursal: 'MCB-02',
    ciudad: 'Maracaibo',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9074',
    usuario: 'usuario75',
    cedula: '24856800',
    correo: 'nelida.garcia74@ejemplo.com',
    nombre: 'Nélida García',
    sucursal: 'VAL-03',
    ciudad: 'Valencia',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9075',
    usuario: 'usuario76',
    cedula: '25062842',
    correo: 'orlando.mendoza75@ejemplo.com',
    nombre: 'Orlando Mendoza',
    sucursal: 'BQT-01',
    ciudad: 'Barquisimeto',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: 'u_9076',
    usuario: 'usuario77',
    cedula: '25269795',
    correo: 'solange.pacheco76@ejemplo.com',
    nombre: 'Solange Pacheco',
    sucursal: 'CBL-02',
    ciudad: 'Ciudad Bolívar',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9077',
    usuario: 'usuario78',
    cedula: '25477659',
    correo: 'edgar.sanchez77@ejemplo.com',
    nombre: 'Edgar Sánchez',
    sucursal: 'MCY-03',
    ciudad: 'Maracay',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9078',
    usuario: 'usuario79',
    cedula: '25686434',
    correo: 'nakary.castillo78@ejemplo.com',
    nombre: 'Nakary Castillo',
    sucursal: 'MTR-01',
    ciudad: 'Maturín',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9079',
    usuario: 'usuario80',
    cedula: '25896120',
    correo: 'jose.villalobos79@ejemplo.com',
    nombre: 'José Villalobos',
    sucursal: 'SCR-02',
    ciudad: 'San Cristóbal',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: 'u_9080',
    usuario: 'usuario81',
    cedula: '26106717',
    correo: 'yolanda.flores80@ejemplo.com',
    nombre: 'Yolanda Flores',
    sucursal: 'CCS-03',
    ciudad: 'Caracas',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9081',
    usuario: 'usuario82',
    cedula: '26318225',
    correo: 'franklin.salazar81@ejemplo.com',
    nombre: 'Franklin Salazar',
    sucursal: 'MCB-01',
    ciudad: 'Maracaibo',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9082',
    usuario: 'usuario83',
    cedula: '26530644',
    correo: 'belkis.perez82@ejemplo.com',
    nombre: 'Belkis Pérez',
    sucursal: 'VAL-02',
    ciudad: 'Valencia',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9083',
    usuario: 'usuario84',
    cedula: '26743974',
    correo: 'freddy.moreno83@ejemplo.com',
    nombre: 'Freddy Moreno',
    sucursal: 'BQT-03',
    ciudad: 'Barquisimeto',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: 'u_9084',
    usuario: 'usuario85',
    cedula: '26958215',
    correo: 'morella.marcano84@ejemplo.com',
    nombre: 'Morella Marcano',
    sucursal: 'CBL-01',
    ciudad: 'Ciudad Bolívar',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9085',
    usuario: 'usuario86',
    cedula: '27173367',
    correo: 'eleazar.martinez85@ejemplo.com',
    nombre: 'Eleazar Martínez',
    sucursal: 'MCY-02',
    ciudad: 'Maracay',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9086',
    usuario: 'usuario87',
    cedula: '27389430',
    correo: 'maria.silva86@ejemplo.com',
    nombre: 'María Silva',
    sucursal: 'MTR-03',
    ciudad: 'Maturín',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9087',
    usuario: 'usuario88',
    cedula: '27606404',
    correo: 'carlos.zambrano87@ejemplo.com',
    nombre: 'Carlos Zambrano',
    sucursal: 'SCR-01',
    ciudad: 'San Cristóbal',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: 'u_9088',
    usuario: 'usuario89',
    cedula: '27824289',
    correo: 'zulay.ramirez88@ejemplo.com',
    nombre: 'Zulay Ramírez',
    sucursal: 'CCS-02',
    ciudad: 'Caracas',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9089',
    usuario: 'usuario90',
    cedula: '28043085',
    correo: 'wilmer.vargas89@ejemplo.com',
    nombre: 'Wilmer Vargas',
    sucursal: 'MCB-03',
    ciudad: 'Maracaibo',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9090',
    usuario: 'usuario91',
    cedula: '28262792',
    correo: 'deisy.rodriguez90@ejemplo.com',
    nombre: 'Deisy Rodríguez',
    sucursal: 'VAL-01',
    ciudad: 'Valencia',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9091',
    usuario: 'usuario92',
    cedula: '28483410',
    correo: 'anibal.rivas91@ejemplo.com',
    nombre: 'Aníbal Rivas',
    sucursal: 'BQT-02',
    ciudad: 'Barquisimeto',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: 'u_9092',
    usuario: 'usuario93',
    cedula: '28704939',
    correo: 'rosalba.colmenares92@ejemplo.com',
    nombre: 'Rosalba Colmenares',
    sucursal: 'CBL-03',
    ciudad: 'Ciudad Bolívar',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9093',
    usuario: 'usuario94',
    cedula: '28927379',
    correo: 'luis.hernandez93@ejemplo.com',
    nombre: 'Luis Hernández',
    sucursal: 'MCY-01',
    ciudad: 'Maracay',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9094',
    usuario: 'usuario95',
    cedula: '29150730',
    correo: 'elena.guerra94@ejemplo.com',
    nombre: 'Elena Guerra',
    sucursal: 'MTR-02',
    ciudad: 'Maturín',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9095',
    usuario: 'usuario96',
    cedula: '29374992',
    correo: 'antonio.quintero95@ejemplo.com',
    nombre: 'Antonio Quintero',
    sucursal: 'SCR-03',
    ciudad: 'San Cristóbal',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: 'u_9096',
    usuario: 'usuario97',
    cedula: '29600165',
    correo: 'milagros.lopez96@ejemplo.com',
    nombre: 'Milagros López',
    sucursal: 'CCS-01',
    ciudad: 'Caracas',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: 'u_9097',
    usuario: 'usuario98',
    cedula: '29826249',
    correo: 'ramon.rojas97@ejemplo.com',
    nombre: 'Ramón Rojas',
    sucursal: 'MCB-02',
    ciudad: 'Maracaibo',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: 'u_9098',
    usuario: 'usuario99',
    cedula: '30053244',
    correo: 'yenifer.suarez98@ejemplo.com',
    nombre: 'Yenifer Suárez',
    sucursal: 'VAL-03',
    ciudad: 'Valencia',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: 'u_9099',
    usuario: 'usuario100',
    cedula: '30281150',
    correo: 'wladimir.torres99@ejemplo.com',
    nombre: 'Wladimir Torres',
    sucursal: 'BQT-01',
    ciudad: 'Barquisimeto',
    plan: 'Plata',
  ),
];

// ── Atajos para armar pruebas sin recorrer la lista a mano ────────────────

/// Las sucursales que existen en el juego de prueba, ordenadas.
List<String> get sucursalesDePrueba =>
    (cienPersonas.map((p) => p.sucursal).toSet().toList()..sort());

/// Los planes que existen.
List<String> get planesDePrueba =>
    (cienPersonas.map((p) => p.plan).toSet().toList()..sort());

/// Las de una sucursal. Para probar el envío segmentado.
List<PersonaDePrueba> deLaSucursal(String sucursal) =>
    cienPersonas.where((p) => p.sucursal == sucursal).toList();

/// Las de un plan.
List<PersonaDePrueba> delPlan(String plan) =>
    cienPersonas.where((p) => p.plan == plan).toList();

/// Buscar por cédula, que es el caso de uso que motivó todo el modelo de alias:
/// el emisor conoce la cédula y no el `userId`.
PersonaDePrueba? porCedula(String cedula) {
  for (final p in cienPersonas) {
    if (p.cedula == cedula) return p;
  }
  return null;
}

/// Entrar como la enésima. `porUsuario('usuario7')` o `laNumero(7)` — lo mismo.
PersonaDePrueba? porUsuario(String usuario) {
  for (final p in cienPersonas) {
    if (p.usuario == usuario) return p;
  }
  return null;
}

/// La enésima, de 1 a 100.
PersonaDePrueba? laNumero(int n) =>
    (n < 1 || n > cienPersonas.length) ? null : cienPersonas[n - 1];

/// Buscar por parecido en el nombre, que es lo que hace la consola.
List<PersonaDePrueba> buscarPorNombre(String texto) {
  final t = texto.trim().toLowerCase();
  if (t.isEmpty) return const [];
  return cienPersonas
      .where((p) => p.nombre.toLowerCase().contains(t))
      .toList();
}
